// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package ds.service1;

public interface ContaminateCheckOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.ContaminateCheck)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 level = 2;</code>
   */
  int getLevel();
}
