// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package ds.service1;

public interface ContaminateLimitOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service1.ContaminateLimit)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 limit = 25;</code>
   */
  int getLimit();
}
