// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package ds.service1;

/**
 * Protobuf enum {@code service1.PipeShutdown}
 */
public enum PipeShutdown
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>OPEN = 0;</code>
   */
  OPEN(0),
  /**
   * <code>CLOSED = 1;</code>
   */
  CLOSED(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>OPEN = 0;</code>
   */
  public static final int OPEN_VALUE = 0;
  /**
   * <code>CLOSED = 1;</code>
   */
  public static final int CLOSED_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static PipeShutdown valueOf(int value) {
    return forNumber(value);
  }

  public static PipeShutdown forNumber(int value) {
    switch (value) {
      case 0: return OPEN;
      case 1: return CLOSED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<PipeShutdown>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      PipeShutdown> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<PipeShutdown>() {
          public PipeShutdown findValueByNumber(int number) {
            return PipeShutdown.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return ds.service1.Service1Impl.getDescriptor().getEnumTypes().get(0);
  }

  private static final PipeShutdown[] VALUES = values();

  public static PipeShutdown valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private PipeShutdown(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:service1.PipeShutdown)
}

