// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package ds.service2;

public interface ResponseLengthMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:service2.ResponseLengthMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 length = 1;</code>
   */
  int getLength();
}
